trigger:
  branches:
    exclude:
      - '*'

pr:
  autoCancel: true
  branches:
    include:
      - '*'

stages:
  # Perform Code Quality Checks
  # - template: templates/code_quality_checks.yml

  # Build Executables
  - stage: 'build'
    displayName: 'Build'
    jobs:
      - job: 'linux-serial'
        displayName: 'Build Linux (Serial/GUI, ubuntu-18.04)'
        pool:
          vmImage: 'ubuntu-18.04' 
        steps:
          - template: templates/build-linux-serial-gui.yml
            parameters:
              ppa: 'beineri/opt-qt-5.13.2-bionic'
              qtver: 513
          - bash: |
              cp build/dissolve tests/
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "tests/"
              ArtifactName: 'linux-tests-serial'
            displayName: 'Publish Serial Test Artifacts'

  # Run System Tests
  - stage: 'system_tests_serial'
    displayName: 'System Tests (Serial)'
    jobs:
      - template: templates/system-tests.yml
        parameters:
          tests: [ 'atomshake', 'broadening', 'calculate_avgmol', 'calculate_cn', 'calculate_dangle', 'calculate_rdf', 'calculate_sdf', 'correlations', 'energyforce1', 'epsr', 'exchangeable', 'pbctorsion', 'rdfmethod' ]
