parameters:
  - name: extraflags
    default: ''
  - name: qtver
    default: 5.15.1
  - name: ftrepo
    default: git://git.sv.nongnu.org/freetype/freetype2.git
  - name: ftglrepo
    default: https://github.com/frankheckenbach/ftgl.git

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
  - script: |
      choco install -y antlr4 ninja winflexbison unzip
    displayName: 'Install Prerequisites'
  - powershell: |
      cd $(System.DefaultWorkingDirectory)
      $url = "https://github.com/projectdissolve/antlr4/releases/download/continuous/antlr4-cpp-runtime-windows.zip"
      $output = "antlr4-cpp-runtime-windows.zip"
      (New-Object System.Net.WebClient).DownloadFile($url, $output)
      unzip $output
    displayName: 'Retrieve ANTLR4 Runtime'
  - script: |
      cd $(Build.SourcesDirectory)
      python -m pip install aqtinstall
      python -m aqt install --outputdir $(Build.BinariesDirectory)\\Qt ${{ parameters.qtver }} windows desktop win64_mingw81 -m qtcore qtgui qtwidgets qtprintsupport
    displayName: 'Install Qt'
  - powershell: |
      python -m pip install conan
    displayName: 'Install Conan' 
  - powershell: |
      $ErrorActionPreference = 'Stop'
      cd $(Build.BinariesDirectory)
      git clone ${{ parameters.ftrepo }} freetype-latest
      mkdir freetype-build
      cd freetype-build
      cmake -G "Ninja" ../freetype-latest -DBUILD_SHARED_LIBS:STRING=ON -DCMAKE_DISABLE_FIND_PACKAGE_HarfBuzz:bool=true -DCMAKE_DISABLE_FIND_PACKAGE_BZip2:bool=true -DCMAKE_DISABLE_FIND_PACKAGE_PNG:bool=true -DCMAKE_DISABLE_FIND_PACKAGE_ZLIB:bool=true -DCMAKE_DISABLE_FIND_PACKAGE_BrotliDec:bool=true
      ninja
    displayName: 'Build FreeType'
  - powershell: |
      $ErrorActionPreference = 'Stop'
      cd $(Build.BinariesDirectory)
      git clone ${{ parameters.ftglrepo }} ftgl-latest
      mkdir ftgl-build
      cd ftgl-build
      $env:FREETYPE_DIR = "$(Build.BinariesDirectory)\freetype-build"
      cmake -G "Ninja" ..\ftgl-latest
      ninja
    displayName: 'Build FTGL'
  - powershell: |
      $ErrorActionPreference = 'Stop'
      $env:Qt5_DIR = "$(Build.BinariesDirectory)\Qt\${{ parameters.qtver }}\mingw81_64"
      $env:PATH += ";$env:Qt5_DIR" + "\bin"
      echo $env:Qt5_DIR
      $env:MINGW_DIR = $env:Qt5_DIR
      $env:INCLUDE += "$(Build.BinariesDirectory)\freetype-latest;"
      $env:LIB += "$(Build.BinariesDirectory)\freetype-build;"
      $env:INCLUDE += "$(Build.BinariesDirectory)\ftgl-latest\src;"
      $env:LIB += "$(Build.BinariesDirectory)\ftgl-build\src;"
      mkdir build
      cd build
      conan install -s compiler="gcc" --remote=conan-center ../
      cmake -G "Ninja" -DGUI:bool=true -DANTLRRUNTIME_DIR:path=$(System.DefaultWorkingDirectory)/antlr4-cpp-runtime ${{ parameters.extraflags }} ../
      ninja libkeywordwidgets.a
      ninja
    displayName: 'Build'
