parameters:
  - name: test
    default: 'atomshake'
  - name: parallel
    default: false

jobs:
  - job:
    condition: eq(parameters.parallel, false)
    displayName: 'Test ${{ parameters.test }} (Serial)'
    pool:
      vmImage: ubuntu-18.04
    steps:
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: 'current'
          specificBuildWithTriggering: true
          downloadType: 'single'
          artifactName: 'linux-tests-serial'
          downloadPath: 'test-artifacts'
        displayName: 'Download Serial Test Artifacts'
      - bash:
          cd test-artifacts
          chmod u+x ./go ./dissolve
          ./go -a -s ./dissolve ${{ parameters.test }}
        displayName: 'Run Test (${{ parameters.test }})'
  - job:
    condition: eq(parameters.parallel, true)
    displayName: 'Test ${{ parameters.test }} (Parallel)'
    pool:
      vmImage: ubuntu-18.04
    steps:
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: 'current'
          specificBuildWithTriggering: true
          downloadType: 'single'
          artifactName: 'linux-tests-parallel'
          downloadPath: 'test-artifacts'
        displayName: 'Download Parallel Test Artifacts'
      - bash:
          cd test-artifacts
          chmod u+x ./go ./dissolve-mpi
          ./go -a -p ./dissolve-mpi ${{ parameters.test }}
        displayName: 'Run Test (${{ parameters.test }})'
