trigger:
  - develop

pr: none

stages:
  # Perform Code Quality Checks
  # - template: templates/code_quality_checks.yml

  # Build and Package Executables
  - stage: 'build'
    displayName: 'Build and Package'
    jobs:
      - job: 'linux_serialgui'
        displayName: 'Build Linux (Serial/GUI, ubuntu-16.04)'
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - template: templates/build-linux-serial-gui.yml
            parameters:
              ppa: 'beineri/opt-qt-5.12.0-xenial'
              qtver: 512
          - template: templates/package-linux-serial-gui.yml
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "packages/"
              ArtifactName: 'linux-artifacts'
            displayName: 'Publish Linux Artifacts'
      - job: 'osx_serialgui'
        displayName: 'Build OSX (Serial/GUI, macos-latest)'
        pool:
          vmImage: 'macos-latest' 
        steps:
          - template: templates/build-osx-serial-gui.yml
          - template: templates/package-osx-serial-gui.yml
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "packages/"
              ArtifactName: 'osx-artifacts'
            displayName: 'Publish OSX Artifacts'
      - job: 'windows_serialgui'
        displayName: 'Build Windows (Serial/GUI, windows-latest)'
        pool:
          vmImage: 'windows-latest' 
        steps:
          - template: templates/build-windows-serial-gui.yml
          - template: templates/package-windows-serial-gui.yml
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "packages/"
              ArtifactName: 'windows-artifacts'
            displayName: 'Publish Windows Artifacts'

  # Deploy
  - stage: 'deploy'
    displayName: 'Deploy'
    jobs:
      - job: 'rename_artifacts'
        displayName: 'Rename Artifacts'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              specificBuildWithTriggering: true
              downloadType: 'single'
              artifactName: 'linux-artifacts'
            displayName: 'Download Linux Artifacts'
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              specificBuildWithTriggering: true
              downloadType: 'single'
              artifactName: 'osx-artifacts'
            displayName: 'Download OSX Artifacts'
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              specificBuildWithTriggering: true
              downloadType: 'single'
              artifactName: 'windows-artifacts'
            displayName: 'Download Windows Artifacts'
          - bash: |
              VERSION=`grep "DISSOLVEVERSION" src/version.h | sed "s/.*\"\(.*\)\"/\1/g"`
              SHORTHASH=`git rev-parse --short HEAD`
              cd ./examples
              ./package-examples -v ${VERSION}-${SHORTHASH}
            displayName: 'Create Example Data Archives'
          - bash: |
              SHORTHASH=`git rev-parse --short HEAD`
              VERSION=`grep "DISSOLVEVERSION" src/version.h | sed "s/.*\"\(.*\)\"/\1/g"`
              # Linux AppImages
              cd $(System.ArtifactsDirectory)/linux-artifacts
              mv -v Dissolve-${SHORTHASH}-x86_64.AppImage Dissolve-${VERSION}-${SHORTHASH}-x86_64.AppImage
              mv -v Dissolve-GUI-${SHORTHASH}-x86_64.AppImage Dissolve-GUI-${VERSION}-${SHORTHASH}-x86_64.AppImage
              cd ../
              # OSX Disk Images
              cd $(System.ArtifactsDirectory)/osx-artifacts
              mv -v Dissolve-GUI-${VERSION}.dmg Dissolve-GUI-${VERSION}-${SHORTHASH}-Catalina.dmg
              cd ../
              # Windows Installer / Zip
              cd $(System.ArtifactsDirectory)/windows-artifacts
              mv -v Dissolve-GUI-${VERSION}-Win64.zip Dissolve-GUI-${VERSION}-${SHORTHASH}-Win64.zip
              mv -v Dissolve-GUI-${VERSION}-Win64.exe Dissolve-GUI-${VERSION}-${SHORTHASH}-Win64.exe
              cd ../
            displayName: 'Rename Artifacts'
#          - bash: |
#              SHORTHASH=`git rev-parse --short HEAD`
#              DATE=`date`
#              ./ci/scripts/update-release -r ${{ github.repository }} -t continuous -n "Continuous Build (${SHORTHASH})" -b "Continuous release from current \`develop\` branch at ${SHORTHASH}. Built ${DATE}." -p -e -u linux-artifacts/*AppImage windows-artifacts/*.exe windows-artifacts/*.zip osx-artifacts/*dmg examples/*zip examples/*.tar.gz
#            displayName: 'Update Continuous Release (GitHub)'
#          - bash: |
#              # TODO
#            displayName: 'Build and Deploy Web'
