trigger:
  branches:
    include:
    - develop
  paths:
    include:
    - web/*
    exclude:
    - /

pr:
  autoCancel: true
  branches:
    include:
      - '*'
  paths:
    include:
    - web/*
    exclude:
    - /

# Only push changes to server and modify short hash if we are running on develop (i.e. the continuous build)
variables:
  isDevelop: $[eq(variables['Build.SourceBranchName'], 'develop')]

stages:
  - stage: 'web'
    displayName: 'Website'
    jobs:
      - job: 'buildweb'
        displayName: 'Update Web'
        pool:
          vmImage: 'ubuntu-18.04'
        steps:
          - template: templates/build-web.yml
            parameters:
              deploy: ${{ eq(variables.isDevelop, 'True') }}
              use_current_hash: ${{ eq(variables.isDevelop, 'True') }}
