name: Pull Request

on:
  pull_request:
    branches:
    - develop

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Build (Linux / Serial+GUI)
      if: matrix.os == 'ubuntu-latest'
      run: |
        ci/ubuntu/build_18.04_serial_gui
        cp build/dissolve tests/
    - name: Build (Linux / Parallel)
      if: matrix.os == 'ubuntu-latest'
      run: |
        ci/ubuntu/build_parallel
        cp build/dissolve-mpi tests/
    - name: Install Qt (Windows)
      if: matrix.os == 'windows-latest'
      uses: jurplel/install-qt-action@v2.2.1
      with:
        version: 5.13.2
        host: windows
        arch: win64_mingw73
    - name: Build (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        ci/windows/build_serial_gui.ps1
    - name: Build (OSX)
      if: matrix.os == 'macos-latest'
      run: |
        ci/osx/build_serial_gui
    - name: Upload Test Artifacts (Linux)
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v1
      with:
        name: test-artifacts
        path: tests/
  system-tests:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        test: [atomshake, broadening, calculate_avgmol, calculate_cn, calculate_dangle, calculate_rdf, calculate_sdf, correlations, energyforce1, epsr, exchangeable, pbctorsion, rdfmethod]
        method: [serial, parallel]
    steps:
    - name: Install Prerequisties (Parallel)
      if: matrix.method == 'parallel'
      run: |
        sudo apt-get install openmpi-bin openmpi-common
    - name: Download Test Artifacts
      uses: actions/download-artifact@v1
      with:
        name: test-artifacts
    - name: Run Test (Serial)
      if: matrix.method == 'serial'
      run: |
        cd test-artifacts
        chmod u+x ./go ./dissolve
        ./go -a -s ./dissolve ${{ matrix.test }}
    - name: Run Test (Parallel)
      if: matrix.method == 'parallel'
      run: |
        cd test-artifacts
        chmod u+x ./go ./dissolve-mpi
        ./go -a -p ./dissolve-mpi ${{ matrix.test }}
